src/main/java/com/apuntesdejava/java/ee/demo/mvc/jpa/entity/DateUtil.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apuntesdejava.java.ee.demo.mvc.jpa.entity;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author diego.silva@apuntesdejava.com
 */
public class DateUtil {

    static final DateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");
    private static final Logger LOG = Logger.getLogger(DateUtil.class.getName());

    public static Date parse(String date) {
        if (date != null && !date.isEmpty()) {
            try {
                return DATE_FORMAT.parse(date);
            } catch (ParseException ex) {
                LOG.log(Level.SEVERE, null, ex);
            }
        }
        return null;
    }

    public static String format(Date date) {
        if (date == null) {
            return null;
        }
        return DATE_FORMAT.format(date);
    }
}

src/main/java/com/apuntesdejava/java/ee/demo/mvc/jpa/entity/Persona.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apuntesdejava.java.ee.demo.mvc.jpa.entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.ws.rs.FormParam;

/**
 *
 * @author dsilva
 */
@Entity
public class Persona implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    private String nombre;

    private boolean activo;

    @Temporal(javax.persistence.TemporalType.DATE)
    private Date fechaNacimiento;

    public String getNombre() {
        return nombre;
    }

    @FormParam("nombre")
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Long getId() {
        return id;
    }

    @FormParam("id")
    public void setId(Long id) {
        this.id = id;
    }

    public boolean isActivo() {
        return activo;
    }

    public void setActivo(boolean activo) {
        this.activo = activo;
    }

    public Date getFechaNacimiento() {
        return fechaNacimiento;
    }

    @FormParam("fecha_nacimiento")
    public void setFechaNacimientoString(String fecha) {
        fechaNacimiento = DateUtil.parse(fecha);
    }

    public String getFechaNacimientoString() {
        return DateUtil.format(fechaNacimiento);
    }

    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Persona)) {
            return false;
        }
        Persona other = (Persona) object;
        return !((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id)));
    }

    @Override
    public String toString() {
        return "Persona{" + "id=" + id + ", nombre=" + nombre + ", activo=" + activo + ", fechaNacimiento=" + fechaNacimiento + '}';
    }

}

src/main/java/com/apuntesdejava/java/ee/demo/mvc/jpa/controller/PersonaController.java
/*
 * Copyright 2016 dsilva.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.apuntesdejava.java.ee.demo.mvc.jpa.controller;

import com.apuntesdejava.java.ee.demo.mvc.jpa.entity.Persona;
import com.apuntesdejava.java.ee.demo.mvc.jpa.service.PersonaFacade;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.mvc.Controller;
import javax.mvc.Models;
import javax.mvc.View;
import javax.ws.rs.BeanParam;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;

/**
 *
 * @author dsilva
 */
@Path("/persona")
@Controller
@RequestScoped
public class PersonaController {

    private static final Logger LOG = Logger.getLogger(PersonaController.class.getName());

    @Inject
    private PersonaFacade personaFacade;
    @Inject
    private Models models;

    @GET
    @View("/WEB-INF/jsp/persona/lista.jsp")
    public void index() {
        LOG.info("Obteniendo lista de personas");
        List<Persona> personas = personaFacade.findAll();
        LOG.log(Level.INFO, "Total obtenidos:{0}", personas.size());
        models.put("personas", personas);

    }

    @POST
    @View("/WEB-INF/jsp/persona/lista.jsp")
    public void actualizar(@BeanParam Persona persona) {
        if (persona.getId() == null || persona.getId() == 0) {
            personaFacade.create(persona);
        } else {
            personaFacade.edit(persona);
        }
        LOG.log(Level.INFO, "Persona creada:{0}", persona);
        index();
    }

    @GET
    @Path("borrar/{id}")
    @View("/WEB-INF/jsp/persona/lista.jsp")
    public void borrar(@PathParam("id") Long id) {
        Persona persona = personaFacade.find(id);
        personaFacade.remove(persona);
        LOG.log(Level.INFO, "Persona borrada:{0}", persona);
        index();
    }

    @GET
    @Path("editar/{id}")
    @View("/WEB-INF/jsp/persona/form.jsp")
    public void editar(@PathParam("id") Long id) {
        Persona persona = personaFacade.find(id);
        models.put("persona", persona);
        LOG.log(Level.INFO, "Persona a editar:{0}", persona);
    }

    @GET
    @Path("nuevo")
    public String nuevo() {
        return "/WEB-INF/jsp/persona/form.jsp";
    }

}

src/main/webapp/WEB-INF/jsp/persona/form.jsp
<%-- 
    Document   : form
    Created on : May 25, 2016, 6:23:58 PM
    Author     : dsilva
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <%@include file="/WEB-INF/jsp/includes/bootstrap.jspf" %>
    </head>
    <body>
        <div class="container">
            <h1>Persona</h1>
            <form method="POST" action="<%= getServletContext().getContextPath()%>/main-app/persona">                
                <input name="id" type="hidden" value="${persona.id}" />
                <div class="form-group">
                    <label>Nombre</label>
                    <input name="nombre" class="form-control" type="text" value="${persona.nombre}"/>
                </div>
                <div class="form-group">
                    <label>Fecha nacimiento</label>
                    <input name="fecha_nacimiento" class="form-control" type="date" value="${persona.fechaNacimientoString}"/><br/>
                </div>
                <button type="submit" class="btn btn-default">Guardar</button>
            </form>
        </div>
    </body>
</html>

src/main/webapp/WEB-INF/jsp/persona/lista.jsp
<%-- 
    Document   : lista
    Created on : May 25, 2016, 5:49:46 PM
    Author     : dsilva
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <%@include file="/WEB-INF/jsp/includes/bootstrap.jspf" %>
    </head>
    <body>
        <div class="container">
            <h1>Personas</h1>
            <ul>
                <li><a href="<%= getServletContext().getContextPath()%>/main-app/persona/nuevo">Nuevo</a></li>
            </ul>
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Fecha nacimiento</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <c:forEach items="${personas}" var="item">
                        <tr>
                            <td>${item.id}</td>
                            <td>${item.nombre}</td>
                            <td><fmt:formatDate value="${item.fechaNacimiento}" pattern="dd/MM/yyyy" /></td>
                            <td>
                                [<a href="<%= getServletContext().getContextPath()%>/main-app/persona/editar/${item.id}">Editar</a>]
                                [<a onclick="return confirm('¿Está seguro de borrar este registro?')" href="<%= getServletContext().getContextPath()%>/main-app/persona/borrar/${item.id}">Borrar</a>]
                            </td>
                        </tr>
                    </c:forEach>
                </tbody>
            </table>
        </div>
    </body>
</html>